modLoader="javafml"
loaderVersion="[40,)"

[[mods]]
modId="mysteriousresurgence"
version="1.0.0"
displayName="神秘复苏"
description="基于小说《神秘复苏》的Minecraft模组"
authors="你的名字"

[[dependencies.mysteriousresurgence]]
modId="forge"
versionRange="[40.0.0,)"
mandatory=true

[[dependencies.mysteriousresurgence]]
modId="minecraft"
versionRange="[1.19.2,1.20)"
mandatory=true
