name: Build Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Make build script executable
      run: chmod +x build.sh
      
    - name: Build with custom script
      run: ./build.sh
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MysteriousResurgence-Mod
        path: build/libs/*.jar
        retention-days: 7
